

class CustomExceptionUser(Exception):
    pass

class RootValidatorException(CustomExceptionUser):
    pass